### ISSUE TITLE
text output of `two.group.unpaired' dabestr object

### ISSUE THREAD

**Issue by marioniepel** [ACCLAB/dabestr#101]
In testing out the package I noticed that for my dataset the text output of a dabestr object is not working correctly. 

When I generate an example using reprex() I get the correct output:

``` r
data <- structure(list(`group` = structure(c(1L, 1L, 1L, 1L, 
1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L), .Label = c("HET-NC", 
"HET-HFFC", "KO-NC", "KO-HFFC"), class = "factor"), `liver_weight` = c(1.30000000002238, 
1.34000000001986, 1.31000000000758, 1.46000000004964, 1.16000000000747, 
1.04000000000829, 1.39000000003149, 2.82000000002197, 2.08000000002276, 
3.02000000005264, 2.34000000001437, 2.71000000009376, 2.10000000003203, 
3.84000000007422, 4.60000000004868, 1.1800000000019, 1.41000000004965, 
1.18000000009746, 1.52000000007503, 1.58000000002913, 1.65000000002449, 
1.47000000003181, 1.64000000007469, 1.34000000009667, 1.42000000004946, 
2.06000000007998, 2.23000000009181, 3.3100000000641, 2.07000000009399, 
1.67000000008604, 2.10000000008102)), row.names = c(NA, -31L), class = c("tbl_df", 
"tbl", "data.frame"))

library("tidyverse")
library("dabestr")
#> Loading required package: magrittr
#> 
#> Attaching package: 'magrittr'
#> The following object is masked from 'package:purrr':
#> 
#>     set_names
#> The following object is masked from 'package:tidyr':
#> 
#>     extract

two.group.unpaired <- dabest(data,
                        group, 
                        liver_weight,
                        idx = c("HET-HFFC", "KO-HFFC"),
                        paired = FALSE)

two.group.unpaired
#> dabestr (Data Analysis with Bootstrap Estimation in R) v0.3.0
#> =============================================================
#> 
#> Good morning!
#> The current time is 10:29 AM on Sunday January 31, 2021.
#> 
#> Dataset    :  data
#> The first five rows are:
#> # A tibble: 5 x 2
#>   group    liver_weight
#>   <fct>           <dbl>
#> 1 HET-HFFC         2.82
#> 2 HET-HFFC         2.08
#> 3 HET-HFFC         3.02
#> 4 HET-HFFC         2.34
#> 5 HET-HFFC         2.71
#> 
#> X Variable :  group
#> Y Variable :  liver_weight
#> 
#> Effect sizes(s) will be computed for:
#>   1. KO-HFFC minus HET-HFFC

two.group.unpaired.meandiff <- mean_diff(two.group.unpaired)
plot(two.group.unpaired.meandiff)
```

![](https://i.imgur.com/HFIAoly.png)

However, when I execute the code in my console window the first five rows of the data set are not displayed. Below is a screenshot of the console calling the text output via `two.group.unpaired` right after executing `reprex()` to generate the output above:

![image](https://user-images.githubusercontent.com/5176275/106389132-de018400-63af-11eb-92ac-cbc77b41df4a.png)
****

<sup>Created on 2021-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by josesho** [comment]
HI @marioniepel , what version of `tibble` are you using?

**Comment by marioniepel** [comment]
I'm running `tibble_3.0.5`. 

Also, I have a general use question, but I am uncertain where to ask for help. If you are on SO, I can ask there.

**Comment by josesho** [comment]
You can post your general use question here, it might be easier to track. 

I am on SO, and if you deem that forum better for that question, go ahead!

**Comment by marioniepel** [comment]
I'd much rather ask here:

I was trying to call `dabest()` via lapply and passed along a vector with column names I wanted to cycle through as the y-columns (measurements). However, I ran into problems in using a vector/string in the function. Since it looks like you are using the dplyr-style NSE for column names I tried to use embracing with double-curly brackets, but that didn't work as I had hoped.

I generated a quick `reprex` with your example:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dabestr)
#> Loading required package: magrittr

set.seed(54321)

N = 40
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
g1 <- rnorm(N, mean = 120, sd = 25)
g2 <- rnorm(N, mean = 80, sd = 50)
g3 <- rnorm(N, mean = 100, sd = 12)
g4 <- rnorm(N, mean = 100, sd = 50)
gender <- c(rep('Male', N/2), rep('Female', N/2))
dummy <- rep("Dummy", N)
id <- 1: N


wide.data <- 
    tibble::tibble(
        Control1 = c1, Control2 = c2,
        Group1 = g1, Group2 = g2, Group3 = g3, Group4 = g4,
        Dummy = dummy,
        Gender = gender, ID = id)


my.data   <- 
    wide.data %>%
    tidyr::gather(key = Group, value = Measurement, -ID, -Gender, -Dummy)

y_col <- "Measurement"

two.group.unpaired <- 
    my.data %>%
    dabest(Group, {{ y_col }}, 
          # The idx below passes "Control" as the control group, 
          # and "Group1" as the test group. The mean difference
          # will be computed as mean(Group1) - mean(Control1).
          idx = c("Control1", "Group1"), 
          paired = FALSE)


two.group.unpaired.meandiff <- mean_diff(two.group.unpaired)
#> Warning in mean.default(~"Measurement"): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(~"Measurement"): argument is not numeric or logical:
#> returning NA
```

And checking on the list `two.group.unpaired` a glance a y shows that is is listed as `~"Measurement"` and not `~Measurement` as I guess it should be.

![image](https://user-images.githubusercontent.com/5176275/106409768-4fbcea80-640f-11eb-9f6d-d8c7f0dbb353.png)

<sup>Created on 2021-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by josesho** [comment]
ugh I spent a lot of time making dpylr wrappers inside `dabestr` to get NSE syntax ala tidyverse packages. 

Does [this strategy](https://stackoverflow.com/questions/48527446/subset-and-plot-data-by-for-loop-lappy) work?

I'll also have a look around and see what can be done.

**Comment by marioniepel** [comment]
The workaround I went with was just to created a mini-dataframe in the lapply call with a fixed name for the test column. That way I was able to call dabest with the same parameters for each lapply call. I then added back the actual name a `rawplot.ylabel`. There using a character string is obviously supported.

```
test_stats <- lapply(c(8, 9, 11, 13:18, 21:34), function(x) { 
						
	             data <- tibble(data_end[1], test = data_end[[x]])
	             two_group_unpaired <- dabest(data,
	             	                           groups, 
			                                test,
			                 	            idx = c("HET-HFFC", "KO-HFFC"),
			                     	       paired = FALSE )
			   plot(mean_diff(two_group_unpaired), rawplot.ylabel = names(data_end)[x])
	} )
```

With the patchwork library for some arrangement it works really nicely:

![image](https://user-images.githubusercontent.com/5176275/106459531-fa5cf980-645f-11eb-9ed8-985a330df963.png)

**Comment by josesho** [comment]
OK closing for now. I'm not sure if I have the time to do a faceted arrangement as you have built-in for `dabestr`, but perhaps down the line...
