### ISSUE TITLE
Outcomes in WEB and R don't match

### ISSUE THREAD

**Issue by francescastarita** [ACCLAB/dabestr#102]
Hi @josesho,

I am opening a new issue as I don't see an answer to this on the previous issue on the same topic. 

I have run the same paired data (see below) on the website and in R but the results do not match. Do you know why?

In R: Paired mean difference of CS+ (n = 30) minus CS-(n = 30)  0.207 [95CI  -2.04; 2.59]
In WEB: Paired mean difference of CS+ (n = 30) minus CS-(n = 30)  0.207 [95.0%CI 0.0687, 0.388]

This is the raw data:
CS-  | CS+
8.33 | 8.57
1.30 | 1.26
6.57 | 6.57
7.11 | 7.64
7.16 | 7.46
6.69 | 6.44
4.77 | 4.72
3.21 | 3.46
13.17 | 13.17
5.33 | 5.71
3.04 | 2.66
11.74 | 11.64
3.34 | 3.58
4.39 | 3.88
2.90 | 2.84
6.98 | 6.83
7.84 | 8.59
18.94 | 19.86
19.91 | 21.43
8.42 | 8.88
7.41 | 6.82
11.85 | 12.82
4.99 | 5.31
3.51 | 3.79
10.17 | 10.29
6.48 | 6.62
5.95 | 5.85
3.67 | 3.95
2.90 | 3.13
5.50 | 6.02

Thanks,
Francesca

_Originally posted by @francescastarita in https://github.com/ACCLAB/dabestr/issues/94#issuecomment-766978809_

**Comment by josesho** [comment]
Hi,

Sorry for the delay, I am looking into this. I will be consolidating the problem on the earlier issue thread, so closing this for now. Thanks!
