### ISSUE TITLE
Differences in CI estimates from dabestr and Estimationstats.com

### ISSUE THREAD

**Issue by mfarrant** [ACCLAB/dabestr#109]
I have used dabestr and Estimationstats.com with the same csv file of data and get differences in paired mean difference CIs. While I would not expect equality, some of the differences seem fairly substantial, seemingly most evident  for sets where the paired difference is small. E.g.:

Paired mean difference 0.0167 [-3.03; 4.04] – with dabestr
Paired mean difference 0.0167 [-0.978, 1.74] – with Estimationstats 

Why is this? Am I wrong to anticipate a closer correspondence?

control | treated

7.435331 | 9.569463
21.08294 | 17.53477
7.263 | 5.82774
10.20145 | 11.21853
11.18679 | 7.795953
10.65369 | 10.88471
18.93889 | 15.19025
17.36686 | 17.65252
23.82235 | 32.6192
11.69568 | 12.51953
12.77081 | 12.58066
14.01452 | 11.62754
8.249101 | 9.728859
9.489087 | 8.350318
9.321579 | 9.214426
10.02159 | 8.718156
11.84355 | 12.94323
6.098538 | 7.780392

**Comment by mfarrant** [comment]
Oops, should have read the previous posts - looks like this is a recognised issue.

**Comment by josesho** [comment]
Hi @mfarrant,

Thanks for posting this, we are coming quite close to pushing a fix for this! 

Closing this for now.

cf #106 , #107
