### ISSUE TITLE
copyright details for `geom_flat_violin.R` 

### ISSUE THREAD

**Issue by IndrajeetPatil** [ACCLAB/dabestr#11]
`geom_flat_violin` used by Allen and colleagues was written by David Robinson for `R`:
original: https://gist.github.com/dgrtwo/eb7750e74997891d7c20
version with minor fixes: https://github.com/tidyverse/ggplot2/issues/2459

But you are attributing copyright only to Allen et al.-
https://github.com/ACCLAB/dabestr/blob/b2bb127d01c6c3c5edf302132d4fb4e1d5143f13/R/flat_violin.R#L1-L2

**Comment by josesho** [comment]
Thanks for this tip; I will fix this very shortly!

**Comment by josesho** [comment]
This issue has been resolved with #13.
