### ISSUE TITLE
Calculating p-values and mean difference in R

### ISSUE THREAD

**Issue by lingers88** [ACCLAB/dabestr#111]
Hi,

I have been using the excellent estimationstats.com website (https://www.estimationstats.com/#/analyze/paired) to create some Gardner-Altmann plots. I am fairly new to R, but have also been following your vignette (https://github.com/ACCLAB/dabestr/tree/master/vignettes) to then recreate these plots in R. 

Now, I'd like to also calculate the permutation p-values and mean differences effect size R (in the same way that these are calculated and reported on the webpage: https://www.estimationstats.com/#/analyze/paired). 

Is it possible to do this in the dabestr package or by using another package? 

I've copied my code below.

Thank you,
Jamie

-------------------------------------------------------------------------------------------------

#load package
library(dplyr)

#random number generator
set.seed(54321)

#TADU
#state number of subjects, means
N = 6
c1 <- c(0.87, 0.85, 0.75, 0.59, 0.75, 0.46)
g1 <- c(0.89, 0.82, 0.70, 0.84, 0.76, 0.75)
Subject <- c("1", "2", "3", "4", "5", "6")
dummy <- rep("Dummy", N)
id <- 1: N

#convert to wide format
wide.data <- 
  tibble::tibble(
    Low = c1,
    High = g1,
    Participant = Subject,
    Dummy = dummy,
    ID = id)

my.data   <- 
  wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Participant, -Dummy)

head(my.data)

#install.packages("dabestr")
library(dabestr)

#set up data
two.group.paired <- 
  my.data %>%
  dabest(Group, Measurement, 
         idx = c("Low", "High"), 
         paired = TRUE, id.col = ID)

#create estimation plot
two.group.paired %>% 
  mean_diff() %>% 
  plot()

two.group.paired <- two.group.paired %>% 
  mean_diff()

#add colours and aesthetics
plot(two.group.paired,
     color.column = Participant,
     rawplot.ylabel = "Proportion of adult turns",
     axes.title.fontsize = 12,
     palette = c("sienna1", "skyblue4", "mediumseagreen", "brown2", "midnightblue", "mediumpurple2")
)

#summary of mean differences
two.group.paired

#save plot
ggsave("TADU.tiff")

**Comment by josesho** [comment]
Hi,

As noted in the [vignette](https://cran.r-project.org/web/packagTo getes/dabestr/vignettes/using-dabestr.html), you can compute 5 different effect sizes including Cohen's _d_:

> As of dabest v0.3.0, there are five effect sizes available:
> 
> The mean difference, given by mean_diff().
> The median difference, given by median_diff().
> Cohen’s d, given by cohens_d().
> Hedges’ g, given by hedges_g().
> Cliff’s delta, given by cliffs_delta().

We are considering including permuation p-values in a future release, likely with the `coin` package. 

In the meantime, you can use the coin package directly; here is its [vignette](https://cran.r-project.org/web/packages/coin/vignettes/Implementation.pdf).

Hope this helps!

**Comment by lingers88** [comment]
That's great, thank you!
