### ISSUE TITLE
Large dataset -- issue with bootstrap repetitions

### ISSUE THREAD

**Issue by signebray** [ACCLAB/dabestr#123]
I get this error when running dabest on a large data set (>7k samples):

Error in bca.ci(boot.out, conf, index[1L], L = L, t = t.o, t0 = t0.o,  : 
  estimated adjustment 'a' is NA

A google search suggests this is because the number of bootstrap iterations needs to be increased.

**Comment by josesho** [comment]
Hi @signebray ,

You can adjust the bootstraps used with the `reps` argument:

```r
your.tidy.data %>%
  dabest(xcol, ycol, 
         idx = c("Control1", "Group1"), 
         paired = FALSE) %>%
   mean_diff(reps = 10000) 
```

The default value is 5000.
