### ISSUE TITLE
Repeated measures mixed model

### ISSUE THREAD

**Issue by hhnguyen7** [ACCLAB/dabestr#134]
Hi,
How would I approach comparison between two independent groups when within each groups there are subjects with repeated measures that are not periodic and paired?

For example: 
Group A (3 subjects, 10 measurements)
Subject 1: 5 measurements
Subject 2: 3 measurements
Subject 3: 2  measurement

Group B ( 4 subjects, 4 measurements)
Subject 1: 1 measurement
Subject 2: 1 measurement
Subject 3: 1 measurement
Subject 4: 1 measurement

Thank you in advance for your help!

**Comment by josesho** [comment]
Hi @hhnguyen7,

If I understand your design, you will need a multi-level model, which currently cannot be done with `dabestr`. 

You seem to have, within Group A, a repeated measures study, whilst in Group B you simply have a single datapoint for each subject. I would think only the first temporal datapoint of Group A, then would be comparable with Group B.

Hope this helps.
Joses
