### ISSUE TITLE
development version 2023.9.12: Error in if (abs(es) > THRESHOLD) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by lijiawei88** [ACCLAB/dabestr#157]
Hello,

I recently upgraded to development version 2023.9.12 of dabestr and encountered an issue when trying to compute median differences between two unpaired groups. Here is my code:

```{r}
# Define the variables and the counts
devtools::install_github(repo = "ACCLAB/dabestr", ref = "dev")
library(dabestr) # For bootstrap estimation
variables <- c("All Clusters", "F67:M33", "F12:M88")
counts <- c(10, 5, 5)

# Repeat the variables the specified number of times
variable_column <- rep(variables, times = counts)

# Generate random numbers for the value column
value_column <- runif(sum(counts), min = 0, max = 30)

# Create the dataframe
data_df <- data.frame(
  variable = variable_column,
  value = value_column
)
cluster.labels <- c("F67:M33", "F12:M88")


# Prepare data for unpaired analysis and calculate median difference
two.group.unpaired <-  load(data_df, 
                            x= variable, y= value,
         idx = c("All Clusters", cluster.labels))

  two.group.unpaired.mediandiff = median_diff(two.group.unpaired, perm_count = 5000)
```

It gives a error:
Error in if (abs(es) > THRESHOLD) { : missing value where TRUE/FALSE needed

Could you please provide some clarification on this?

Thank you!

**Comment by sunroofgod** [comment]
Hi @lijiawei88!

This seems to be another bug with mismatch Ns not being correctly handled for the calculation of p-values and permutation tests. 

This issue has been addressed and resolved in the latest version that is available on the development branch.

You may update your version of dabestr to the development version via:
```R
devtools::install_github(repo = "ACCLAB/dabestr", ref = "dev")
```

Thanks for bringing attention to these issues related to mismatch Ns thus far. Hope this helps!

**Comment by lijiawei88** [comment]
> Hi @lijiawei88!
> 
> This seems to be another bug with mismatch Ns not being correctly handled for the calculation of p-values and permutation tests.
> 
> This issue has been addressed and resolved in the latest version that is available on the development branch.
> 
> You may update your version of dabestr to the development version via:
> 
> ```r
> devtools::install_github(repo = "ACCLAB/dabestr", ref = "dev")
> ```
> 
> Thanks for bringing attention to these issues related to mismatch Ns thus far. Hope this helps!

Thanks! It works!
