### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by brembs** [ACCLAB/dabestr#163]
Thanks for a great package!
Been using dabestr for quite some time now and the version change from 0.3.0 to 2023.09.12 crashed our code. 
Apparently, "dabestr" was changed to "dabestr_plot", but when I replace one with the other, I get the error message that what I'm trying to plot is not a dabestr object. Is there a changelog somewhere that details what I need to do to make my old code run with the new version?
Many thanks in advance!

**Comment by sunroofgod** [comment]
Hi @brembs sorry for the late reply!

dabestr v2023.9.12 more or less stuck to the old api (with the sequentially calling of `load()`, followed by the appropriate `effect_size()` functions, followed by the `dabest_plot()` function) but the functions themselves have changed quite drastically. 

You may find the changelog [here](https://acclab.github.io/dabestr/news/index.html) useful. Alternatively, you may also look through the tutorials [here](https://acclab.github.io/dabestr/articles/tutorial_basics.html) for how the new functions are being called.

Hope this helps! Feel free to let me know if you still run into any issues. 

Lastly, there are currently some persistent bugs with v2023.9.12. The fixes for the bugs are currently only available in the dev version. You may obtain the dev version via the following:

```R
devtools::install_github(repo = "ACCLAB/dabestr", ref = "dev")
```

**Comment by brembs** [comment]
Many thanks for the links! I'll go over them and try and fix our code. This may take some time. I'll get back in case there is something I'm missing. Thanks again for dabestr and for keeping up with the user queries!

**Comment by brembs** [comment]
Tutorial and changelog helped a lot, many thanks! 
Do I understand this correctly that now dabestr works only when the N is identical in both groups?

**Comment by sunroofgod** [comment]
Yes! For v2023.9.12 of dabestr, that is correct. However, this has been fixed in the dev branch version and you can now do it for unequal Ns across all groups. You can access the dev version by running:

```R
devtools::install_github(repo = "ACCLAB/dabestr", ref = "dev")
```

You may keep an eye on both the repository and the documentation for upcoming updates. We'll be releasing a new version that incorporates all the fixes in the near future.

**Comment by brembs** [comment]
Excellent! I'll just wait until the new version comes out! It was very easy to upgrade, thanks again for the support and your great package!

**Comment by sunroofgod** [comment]
No worries at all! If you ever have more questions or run into any issues, feel free to reach out.

Additionally, thanks for using our dabestr package. Your kind words and support means a lot to us :) Happy coding!
