### ISSUE TITLE
Issue with multiple between-group comparisons

### ISSUE THREAD

**Issue by MarkKramer** [ACCLAB/dabestr#167]
I'm trying to complete a between-group analysis (i.e. control group vs. test group) across 3 different control conditions. You have an excellent option for this (final plot on: https://acclab.github.io/dabestr/articles/tutorial_basics.html), but I get the following error:

"Error in PermutationTest(ctrl_measurement, test_measurement, effect_size = effect_size_type,  : 
  The two arrays do not have the same length."

Is there perhaps something I am not doing correctly? To me the arrays should not need the same length.

Kind regards,

Mark

**Comment by MarkKramer** [comment]
Per my comment above, it seems to do this even when I try just a simple between-group comparison just for the control group (n=64) vs. the test1 group (n=15). I get the same error.

**Comment by sunroofgod** [comment]
Hi @MarkKramer, sorry for the late reply!

This issue has been addressed previously and resolved in the latest version that is available on the development branch.

You may update your version of dabestr to the development version via:
```R
devtools::install_github(repo = "ACCLAB/dabestr", ref = "dev")
```
You may also see the issue thread regarding the same issue here: https://github.com/ACCLAB/dabestr/issues/154.

Hope this helps :)

**Comment by Jacobluke-** [comment]
Issue closed with no response for a long time
