### ISSUE TITLE
Sinaplot

### ISSUE THREAD

**Issue by fobinf** [ACCLAB/dabestr#23]
I like your idea! I seems that maybe you are actually not making a swarm plot, but, wisely, a Sina Plot. The name should be changed in the readme, as well as stated in your publication. Swarm plots have a branching structure, which I don't see in your plots. Sina plots have random jitter within the distribution (like jitter in a violin plot). For small size it is hard to see the difference, but clear for many. Nonetheless I suggest the Sinaplot.

**Comment by josesho** [comment]
Thanks for your comment. `dabestr` does allow the user a choice between swarmplots and sinaplots for the presentation of rawdata. The example plots actually do use a [quasirandom method](https://cran.r-project.org/web/packages/ggbeeswarm/vignettes/usageExamples.pdf) from the `beeswarm` package. 

In our publication we are advocating for swarmplots (and sinaplots) as best practice. The choice of which one is left to the analyst, depending on the data.
