### ISSUE TITLE
Misaligned mean difference line

### ISSUE THREAD

**Issue by johannesbjork** [ACCLAB/dabestr#29]
When plotting proportional data, I found that the mean difference line is not aligned to the mean difference distribution. 

Here is an example.

```
df <- cbind(data.frame(value=sample(1:9, 100, replace= TRUE)/10),data.frame(grp=sample(c("A","B"),100,replace=T)))

plot(dabest(df, x = grp, y = value, idx = c("A","B")))
```
<img width="864" alt="screen shot 2019-02-28 at 10 47 24 pm" src="https://user-images.githubusercontent.com/6168782/53615198-d83f0a80-3baa-11e9-9ad6-f6f9eefed59c.png">

**Comment by josesho** [comment]
Hi @johannesbjork , could you provide a [minimally reproducible example](https://gist.github.com/hadley/270442)? This would help me in trying to debug the issue. 

Thanks!

**Comment by josesho** [comment]
Sorry for the delay. I'm seeing this on my end as well; definitely a bug. 

You can use [www.estimationstats.com](www.estimationstats.com) to produce the correct Gardner-Altman plot. 

Will let you know once I've squashed this bug!

PS. We are working on more effective ways to display proportions. (Here, I assume each data point is a proportion already?)

**Comment by josesho** [comment]
More troubleshooting.

```r
library(tidyverse)

set.seed(12345)
df <- cbind(data.frame(value=sample(1:9, 100, replace = TRUE)/10), 
            data.frame(grp=sample(c("A","B"), 100, replace = T))
            )
df %>% group_by(grp) %>% count()
```

```
# A tibble: 2 x 2
# Groups:   grp [2]
  grp       n
  <fct> <int>
1 A        54
2 B        46
```

Using `dabestr` to analyse this....
```r
library(dabest)

df_analysed <- dabest(df, x = grp, y = value, idx = c("A", "B"))
df_analysed
```
produces

```
DABEST (Data Analysis with Bootstrap Estimation) v0.2.1
============================================================

Variable: value 

Unpaired mean difference of B (n=54) minus A (n=100)
 -0.0127 [95CI  -0.0986; 0.0774]


5000 bootstrap resamples.
All confidence intervals are bias-corrected and accelerated.
```

Note how the N for `A` is now 100 instead of 54. The bug likely lies in how the `data.frame` is being handled....

**Comment by josesho** [comment]
This is likely to be related to #30 . For some reason, unequal group sizes jams up the munging....

**Comment by josesho** [comment]
Hi @johannesbjork ,

This bug occurs because `grp` is used [internally](https://github.com/ACCLAB/dabestr/blob/e601bbbc8e5cd0bbdf368139b103637e936d2c14/R/main.R#L287). To quickly and simply mitigate this, simply change the x-column to another name.


```r
library(dabest)

set.seed(12345)
df <- cbind(data.frame(value=sample(1:9, 100, replace = TRUE)/10), 
           # we rename the `grp` column to `ggrp`.
            data.frame(ggrp=sample(c("A","B"), 100, replace = T)) 
)


df_analysed <- dabest(df, x = ggrp, y = value, idx = c("A", "B"))
plot(df_analysed)
```

 
![out](https://user-images.githubusercontent.com/12838917/60173373-2a362b00-9841-11e9-99a7-a19c0a911a53.png)

**Comment by josesho** [comment]
Pull request #43 fixes this. Run

```r
devtools::install.github('ACCLAB/dabestr')
```

to install `v0.2.1.9000`, which is the beta release. This should be on CRAN in a week or so.

**Comment by Gushumes** [comment]
Hello. How have you solved this problem with the code here:
https://cran.r-project.org/web/packages/dabestr/vignettes/using-dabestr.html
