### ISSUE TITLE
Setting function to Cohen's d or Hedges' g

### ISSUE THREAD

**Issue by Santihago** [ACCLAB/dabestr#31]
Hi,

In a paired comparison, is it possible to set the function (`func =`) to obtain the Cohen's d or Hedges g effect size, as it is on the website version?

On the website version, I can choose between mean, median, Cohen's d and Hedges' d. On R, I tried with `func = mean` and` func = median`, and both work. But what argument should I input to have the Cohen's d effect size, as in the website?

Thank you very much.

`paired_mean_diff <- data %>% 
dabest(., x, y, idx = c("Control", "Group"), paired = TRUE, id.column = id, ci = 95, func = mean)
`

**Comment by josesho** [comment]
Hi @Santihago ,

Thanks for using our package!

Unfortunately standardized effect sizes have not been implemented in dabestr yet. We do plan on doing so but we don't have a deadline yet! 

An aside: the `func` argument in `dabest()` applies that function to both the control and test groups, and then takes the difference. So even if we wrote a custom Hedges' _g_ function, for example, it can't be passed along like this. (I have ideas on how to tweak the current API, stay tuned!)

The [Python version] of dabestr features Cohen's _d_ and Hedges' _g_; if you are comfortable with Python you could have a look at that.

Regards,
Joses

**Comment by Santihago** [comment]
Thank you @josesho, I will have a look at the Python version. Good luck with the development and thank you for the great package!
