### ISSUE TITLE
Finetune application of ggplot themes

### ISSUE THREAD

**Issue by josesho** [ACCLAB/dabestr#33]
While we are able to [apply themes](https://github.com/ACCLAB/dabestr/blob/caf8c8d4bafcbfb9f6709417797de36b0401cfd5/R/plot.R#L162) when creating a plot, we need to finetune the theme application (remove gridlines etc).

**Comment by frannasc** [comment]
Congrats on a great package! I'm trying to use it to make the figures for my next publication.
Is it possible to select the colors to use inside a palette for the rawplot? 
For eg to specify which two colors from "Dark2" you want for the dots in the rawplot? 
plot(multi.group, color.column = Gender,
     palette = "Dark2" # The default is "Set2".
     )
Or for the color of the error distribution in the effsize plot?
Thanks in advance

**Comment by josesho** [comment]
Color selection is a feature we plan to include in v0.3.0. Thanks!

**Comment by josesho** [comment]
Fixed with PR #77
