### ISSUE TITLE
requirement for ellipsis version 0.2.0.1 

### ISSUE THREAD

**Issue by DanInUU** [ACCLAB/dabestr#46]
When I test the example code with plot (unpaired_mean_diff), there is a error happens, said :**Error: 'check_dots_empty' is not an exported object from 'namespace:ellipsis'**      . So I checked the **sessionInfo( )**, and find that the ellipsis v0.1.0, I tried to update to the new version , and then the plots shows up.

**Comment by josesho** [comment]
Noted with thanks. Will include a version in `REQUIREMENTS`.
