### ISSUE TITLE
contradictory results

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [ACCLAB/dabestr#48]
Dear Adam and Joses,

it seems there is a bug in your program.
I have the attached paired data set and receive the contradictory results: 
The paired Hedges' g between TS_hist and TS_a is 0.174 [95.0%CI -0.134, 0.483].
The two-sided P value of the Wilcoxon test is 0.000693. 
Program JASP gives d = 0.35 with 95% CI from 0.13 to 0.57 and the same p = 0.00069
[TS.zip](https://github.com/ACCLAB/dabestr/files/3374400/TS.zip)

Best regards,
Nikita

**Comment by josesho** [comment]
Hi @NikitaKhromov-Borisov 

Thanks for raising this issue! As noted in the [Reporting Bugs](https://github.com/ACCLAB/dabestr#bugs) section of our Readme, could you provide a  reproducible example (aka [reprex](https://www.tidyverse.org/help/))? Specifically, the `R` code you used to obtain the `dabestr` results.

This will help us in tracing if there is indeed a bug. 

Thanks!

**Comment by josesho** [comment]
> The paired Hedges' g between TS_hist and TS_a is 0.174 [95.0%CI -0.134, 0.483].

As of right now, `dabestr` does not produce standardized effect sizes. How did you obtain this?

**Comment by NikitaKhromov-Borisov** [comment]
I told about Estimation Stat
https://www.estimationstats.com/#/
NKh



ср, 10 июл. 2019 г. в 06:07, Joses W. Ho <notifications@github.com>:

**Comment by josesho** [comment]
OK, I think there's been a misunderstanding. This forum is for the R package `dabestr`. WE've just set up a brand-new [Google Groups](https://groups.google.com/forum/#!forum/estimationstats) for "help-wanted" emails specifically for our estimationstats.com webapp.

Please send an email with the attached data to estimationstats@googlegroups.com, and it will appear on the forum.

I will add: I have no idea how you used JASP to produce those results, so unless you can work out step-by-step what was done in JASP, I am afraid I cannot help you much, except by showing step-by-step what is done in DABEST.
