### ISSUE TITLE
Unable to change effsize.ylim

### ISSUE THREAD

**Issue by silasprincipe** [ACCLAB/dabestr#52]
Hi! I'm having trouble in changing the scale of y-axis of the effect size in a two-independent DABEST plot. I have two different plots to construct, and I want them to have the same scale sizes to facilitate understanding. 

![tgu_kit](https://user-images.githubusercontent.com/53846571/62591806-3503c700-b8a7-11e9-8039-836268c8e5d1.png)
![tgu_poc](https://user-images.githubusercontent.com/53846571/62591814-39c87b00-b8a7-11e9-925d-23ca8463ff4e.png)

Here is the code with some data to exemplify:

cont1 <- c(17, 18.6, 21, 27, 13, 26, 19.5, 14.8, 12, 23,  10, 14.6, 23, 24)
treat1 <- c(30, 24, 18, 21, 12, 27.1, 25.5, 29, 45, 22, 29.3, 34, 22, 13)
cont2 <- c(6, 6, 22, 20, 15, 21, 13, 6, 6, 19,  6, 6, 31, 29)
treat2 <- c(6.1, 25, 22, 20, 15, 21, 13,  30,  60, 19,  6, 6, 31, 29)
#### First dataset
data.a <- tibble::tibble(Control = cont1, Treatment = treat1)
data.a.f   <- 
  data.a %>%
  tidyr::gather(key = Group, value = Measurement)
dabest.a <- 
  data.a.f %>%
  dabest(Group, Measurement, 
         # The idx below passes "Control" as the control group, 
         # and "Group1" as the test group. The mean difference
         # will be computed as mean(Group1) - mean(Control1).
         idx = c("Control", "Treatment"), 
         paired = FALSE)
plot(dabest.a,
     rawplot.ylabel = "Concentration",
     effsize.ylabel = "Mean difference", palette = "Dark2",
     rawplot.markersize = 4, rawplot.groupwidth = 0.2,
     rawplot.ylim = c(10, 50),
     effsize.ylim = c(0, 30))
#### Second dataset
data.b <- tibble::tibble(Control = cont2, Treatment = treat2)
data.b.f   <- 
  data.b %>%
  tidyr::gather(key = Group, value = Measurement)
dabest.b <- 
  data.b.f %>%
  dabest(Group, Measurement, 
         # The idx below passes "Control" as the control group, 
         # and "Group1" as the test group. The mean difference
         # will be computed as mean(Group1) - mean(Control1).
         idx = c("Control", "Treatment"), 
         paired = FALSE)
plot(dabest.b,
     rawplot.ylabel = "Concentration",
     effsize.ylabel = "Mean difference", palette = "Dark2",
     rawplot.markersize = 4, rawplot.groupwidth = 0.2,
     rawplot.ylim = c(10, 50),
     effsize.ylim = c(0,30))

Another question: how do I change the scale interval (for example, by 5, not 10). Thanks!

**Comment by josesho** [comment]
Hi, 

I would suggest using a [Cumming plot](https://acclab.github.io/DABEST-python-docs/robust-beautiful.html#one-way-anova-multiple-comparisons-multi-two-group-estimation-plot) rather than two [Gardner-Altman plots](https://acclab.github.io/DABEST-python-docs/robust-beautiful.html#introducing-the-estimation-plot) to achieve what you want.

```r
all.data <- tibble::tibble(Control1 = cont1, Treatment1 = treat1,
                           Control2 = cont2, Treatment2 = treat2)

all.data.tidy <-
  all.data %>%
  tidyr::gather(key = Group, value = Measurement)

dabest.all.data <- 
  all.data.tidy %>%
  dabest(Group, Measurement,
         idx = list(c("Control1", "Treatment1"),
                    c("Control2", "Treatment2")),
         paired = FALSE)

plot(dabest.all.data)
```
![cumming_demo](https://user-images.githubusercontent.com/12838917/62597788-b85e0080-b919-11e9-9c1f-f89927023c17.png)

If, however, you want two Gardner-Altman plots, then what you have done above (setting `rawplot.ylim`) works. The nature of the Gardner-Altman plots is such that one can only set the ylims for the rawdata plot (on the left); the axes with the effect size and confidence interval is, by design, aligned to the axes on the left and currently cannot be set.

**Comment by josesho** [comment]
> Another question: how do I change the scale interval (for example, by 5, not 10). Thanks!

To the best of my knowledge, this is effectively not possible now. (We use [`cowplot`](https://github.com/wilkelab/cowplot) to stitch the raw swarmplot with the effect size plot. You might be able to isolate the axes, and then using ggplot's [`scale_y_continuous`](https://ggplot2.tidyverse.org/reference/scale_continuous.html) to set the tick breaks, but I'm not sure how yet.)

**Comment by silasprincipe** [comment]
Thanks @josesho !
