### ISSUE TITLE
Median difference in R

### ISSUE THREAD

**Issue by mjw349** [ACCLAB/dabestr#59]
Hello,

I have been using your website interface to graph my data but would like to switch over to graphing in R to take advantage of choosing some details, like the color of the plots. Is there a function to analyze the data with the median (instead of the default mean) in R? I can't seem to find it, if it's out there already!

Thanks for this wonderful resource!
Miwa

**Comment by josesho** [comment]
Hi @mjw349 ,

As noted in the when you run  
```r 
library(dabestr)
help(dabest)
```
in the Examples section, you will find

```r
dabest(iris, Species, Petal.Width,
            idx = c("setosa", "versicolor", "virginica"),
            paired = FALSE,
            func = median)
```

Feel free to re-open if there are any more problems.
