### ISSUE TITLE
Import plyr

### ISSUE THREAD

**Issue by thomasp85** [ACCLAB/dabestr#66]
The new version of ggplot2 no longer depend on plyr. dabestr has somehow been able to have `plyr::` calls in its code without explicitly depending on plyr, but these will now break as plyr is no longer present on a clean system.

To fix this, add plyr to Imports in the DESCRIPTION file and submit to CRAN

**Comment by josesho** [comment]
Thanks for the headsup, will do as advised shortly!

**Comment by josesho** [comment]
Addressed with v0.3.4
