### ISSUE TITLE
Removing the distribution plot

### ISSUE THREAD

**Issue by giuappel** [ACCLAB/dabestr#69]
Hi,

I want to combine 9 plots in one graph, but I notice that the graph was too big.
So is it possible to remove the distribution plot and just present the effect size plot? 

And how I can remove the legends and the  xlab and ylab?

Thanks
Cheers,

Giulliana

**Comment by josesho** [comment]
Hi @giuappel ,

As you did not include a [reproducible example](https://stackoverflow.com/a/5963610), I will attempt to infer your problem.

Let's say you have a dataset as below:

```r
library(dplyr)

set.seed(54321)

N = 40
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
c3 <- rnorm(N, mean = 100, sd = 25)
c4 <- rnorm(N, mean = 100, sd = 50)
c5 <- rnorm(N, mean = 100, sd = 25)
c6 <- rnorm(N, mean = 100, sd = 50)

g1 <- rnorm(N, mean = 100, sd = 20)
g2 <- rnorm(N, mean = 100, sd = 30)
g3 <- rnorm(N, mean = 100, sd = 40)
g4 <- rnorm(N, mean = 100, sd = 50)
g5 <- rnorm(N, mean = 100, sd = 50)
g6 <- rnorm(N, mean = 100, sd = 40)


wide.data <- 
  tibble::tibble(
    Control1 = c1, Control2 = c2, Control3 = c3,
    Control4 = c4, Control5 = c5, Control6 = c6,

    Test1 = g1, Test2 = g2, Test3 = g3,
    Test4 = g4, Test5 = g5, Test6 = g6,
    )


my.data   <- 
  wide.data %>%
  tidyr::gather(key = Group, value = Measurement)

my.data
```

Output:
```shell
# A tibble: 480 x 2
   Group    Measurement
   <chr>          <dbl>
 1 Control1        95.5
 2 Control1        76.8
 3 Control1        80.4
 4 Control1        58.7
 5 Control1        89.8
 6 Control1        72.6
 7 Control1        57.7
 8 Control1       163. 
 9 Control1       135. 
10 Control1       104. 
# … with 470 more rows
```
The dataset has six pairs of comparisons (Control1 and Test1, Control2 and Test2, etc), and you want to compute the effect sizes for each of the six comparisons.

You could create a single Gardner-Altman plot for each pair, but as you mentioned, it might become hard to tile them horizontally in a visually-pleasing manner.

```r
library(dabestr)
library(cowplot)

two.group.unpaired1 <- 
  my.data %>%
  dabest(Group, Measurement, 
         # The idx below passes "Control" as the control group, 
         # and "Group1" as the test group. The mean difference
         # will be computed as mean(Group1) - mean(Control1).
         idx = c("Control1", "Test1"), 
         paired = FALSE)

a <- plot(two.group.unpaired1)

two.group.unpaired2 <- 
  my.data %>%
  dabest(Group, Measurement, 
         # The idx below passes "Control" as the control group, 
         # and "Group1" as the test group. The mean difference
         # will be computed as mean(Group1) - mean(Control1).
         idx = c("Control1", "Test1"), 
         paired = FALSE)

b <- plot(two.group.unpaired2)

plot_grid(plotlist = list(a, b))
```
![image](https://user-images.githubusercontent.com/12838917/77984088-3a84b480-7343-11ea-891b-995b19d2c483.png)


What you should do instead is create a **multi-two group plot**. See the corresponding section in the [official dabestr vignette](https://cran.r-project.org/web/packages/dabestr/vignettes/using-dabestr.html).

```r
multi.two.group.unpaired <- 
  my.data %>%
  dabest(Group, Measurement, 
         # The idx below passes "Control" as the control group, 
         # and "Group1" as the test group. The mean difference
         # will be computed as mean(Group1) - mean(Control1).
         idx = list(c("Control1", "Test1"), 
                    c("Control2", "Test2"),
                    c("Control3", "Test3"),
                    c("Control4", "Test4"),
                    c("Control5", "Test5"),
                    c("Control6", "Test6")),
         paired = FALSE)

plot(multi.two.group.unpaired, palette="Paired")
```
![image](https://user-images.githubusercontent.com/12838917/77984276-acf59480-7343-11ea-94de-e5ad32222d58.png)

If it is still too crowded, you can use a vector graphics software to select the lower effect size axes.

_Note that for your case, with 9 pairs of comparisons, you will need to create two plots as  all ggplot2 palettes only have a maximum color range of 12 groups. Future dabestr versions will allow custom color palettes._

To remove the ylab, simply run

```r
plot(multi.two.group.unpaired, palette="Paired", rawplot.ylabel = "", effsize.ylabel = "")
```
![image](https://user-images.githubusercontent.com/12838917/77984631-b3d0d700-7344-11ea-9fc0-1538c62fc8d8.png)

There is not option yet to remove the xlabs.

If this is not what you were asking, please share a reproducible example.

Hope this helped!
Joses
