### ISSUE TITLE
How to output Cliff's Delta as effect size

### ISSUE THREAD

**Issue by yngmiin** [ACCLAB/dabestr#70]
Hi,

Thanks for the excellent estimation stats package. May I ask how I can output Cliff's Delta as effect size measure in the Gardner-Altman estimation plot? I am new to using dabestr and I apologize if I have missed the method in the package documentation. 

Thank you.

Regards,
Yng Miin Loke

**Comment by josesho** [comment]
Hi,

Currently the dabestr package does not offer standardized effect sizes such as Cliffs' delta. This is currently under development.

If you need to generate such plots, please consider the www.estimationstats.com webapp, or the [Python version](https://github.com/ACCLAB/DABEST-Python) of DABEST.

Thanks,
Joses

**Comment by josesho** [comment]
@yngmiin  v0.3.0 now features standardized effect sizes!
