### ISSUE TITLE
big data

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [ACCLAB/dabestr#75]
your program cannot analyze
[Size.xlsx](https://github.com/ACCLAB/dabestr/files/4493480/Size.xlsx)
 big data
It seems for such a data to use option jitter
Nikita

**Comment by josesho** [comment]
Hi @NikitaKhromov-Borisov ,

Yes, unfortunately your data has n=838, n=3193 for both groups. Already there is a large imbalance between the Ns! 

Thank you for noting the limitation of the swarmplot. As stated in the [reference manual ](https://cran.r-project.org/web/packages/dabestr/dabestr.pdf) on CRAN, you can use the `swarmplot.params` argument to pass along a range of options to `geom_quasirandom()` which is used under the hood to plot the swarmplot. (You can read more about it [here](https://cran.r-project.org/web/packages/ggbeeswarm/vignettes/usageExamples.pdf).
