### ISSUE TITLE
How to remove the legend

### ISSUE THREAD

**Issue by mfarrant** [ACCLAB/dabestr#80]
How can I  get rid of the legend? I tried a ggplot-like command `legend.position = “none”`) but I get: `Error in theme_classic(legend.position = "none") : unused argument (legend.position = "none")`

Thanks

EIDT - OK ignore - just remembered the legend goes if I don't include a `color.column` statement.

**Comment by josesho** [comment]
OK, I do wonder if there is a place to turn off the color legend anyway. I can include a simple flag in the upcoming release of v0.3.0.
