### ISSUE TITLE
palette argument does not work

### ISSUE THREAD

**Issue by Si-Chong** [ACCLAB/dabestr#82]
I try to follow Joses' tutorial: https://cran.r-project.org/web/packages/dabestr/vignettes/using-dabestr.html

I use the code in the tutorial:
```
plot(multi.group, color.column = Gender, palette = c("#FFA500", "sienna4"))
```

But it does not work and gives a warning message:
```
Warning messages:
1: In if (!palette %in% unlist(brewer)) { :
  the condition has length > 1 and only the first element will be used
2: In pal_name(palette, type) : Unknown palette #FFA500sienna4
```

In my own case, my aim is to manually change the colour of rawdata swarmplot. In addition (maybe related or not), I also wish to manually change the colour of slope lines (for example, to "grey"). Any idea how to do it? Thanks!

**Comment by josesho** [comment]
Hi @Si-Chong ,

You will need to upgrade your version of `dabestr` to `v0.2.5`. 

In RStudio, go to Tools > Check for Package Updates.

**Comment by josesho** [comment]
> I also wish to manually change the colour of slope lines (for example, to "grey"). Any idea how to do it? Thanks!

As noted in the help for the `plot.dabest()` function (enter `?plot.dabest` at the R console), you can control slopegraph parameters with the `slopegraph_params` argument, which accepts a list of `keyword = value` pairs that are passed to `ggplot2::geom_line()`.

**Comment by Si-Chong** [comment]
Thank you Joses!
My fault... I indeed should check the package updates. Now solved.

For the second question, could you please give an example? I now use the following but seems not working:
`plot(paired_mean_diff, slopegraph.params = (colour="blue"))`

**Comment by josesho** [comment]
Hi @Si-Chong ,

This seems to be a bug indeed. Unfortunately the `slopegraph.params` isn't parsing this properly. 

I will issue an update with v0.3.0, in the meantime, I am afraid you will have to use a vector graphics software to change the slopegraph colors manually.

**Comment by Si-Chong** [comment]
Thank you Joses! Yes, I am now using photoshop as a solution.
Looking forward to the new version and it could be fantastic if line colour and alpha/transparency could be changed manually. Thank you for the cool package and whole methodology, which is very helpful to my research.
