### ISSUE TITLE
One-Sample t-test

### ISSUE THREAD

**Issue by aleksandernitka** [ACCLAB/dabestr#83]
Hi. The package is amazing and I generally find it very useful. Great job! One issue I am having is, that I cannot run a one-sample t-tests. Is there a way around it and are you planning to introduce such feature?

**Comment by josesho** [comment]
Thank you for your kind words.

We are not planning on introducing this feature. The focus of `dabestr` is effect sizes and their confidence intervals; therefore you need at least two groups to compute some metric of difference.
