### ISSUE TITLE
Changing the shape of data 

### ISSUE THREAD

**Issue by wy-2020** [ACCLAB/dabestr#93]
Hi there,
Thanks for this great package!

I want to change the shape of data for a multi-paired (Cumming Plot). The default shape is the dot. How can I specify the shape of each column data point? For example, my multi-paired plot has four column data point (x-axis classification: group1-low-ability, group1-high-ability, group2-low-ability, group2-high-ability), I want to change the shape of data for the "group1-low-ability" and "group2-low-ability".

any suggestion?
Thank you very much !

**Comment by Ernest861** [comment]
Hi, I had tried to change the shape for the two group compare.
```
mw = dabest(q1, group, `mixing weight`, func = mean, idx=c('HC','BN'), 
                     paired=FALSE,ci=95,reps=5000,seed=12345)

# set the color pal
group.names<-c('BN','HC') 
ylab.color<-c('#FF0000','#000000')
z1.pal<-setNames(ylab.color,group.names)

# change the shape of the raw plot
plot(mw,palette = z1.pal,swarmplot.params=list(shape=1,size = 3),tick.fontsize = 18,axes.title.fontsize = 18)
```
more information in geom_quasirandom {ggbeeswarm}

good luck!
Hui Zheng
BME SMHC Shanghai Jiao Tong University
