### ISSUE TITLE
Effect Sizes

### ISSUE THREAD

**Issue by timothysandhu** [ACCLAB/dabestr#98]
Thanks for making such a great package! 

I'm currently revisiting data which I analyzed with a previous version of the package, looking at two groups with two (paired) sessions each.

When I rerun the analysis with the new version, I get quite different output - as you can hopefully see in the attached image. The top row of plots look identical, but the different plots don't, which makes me think that it's to do with effect size? 

I note that when you updated the package, there was a note that effect size calculation had changed. Is this type of change expected with the new version?

<img width="433" alt="dabest_issue" src="https://user-images.githubusercontent.com/58176991/100636621-d0853a80-3329-11eb-8ee0-d34ad93a7324.png">

Thanks in advance!

**Comment by josesho** [comment]
Hi @timothysandhu , do you have a reproducible example to generate these different plots? What was the older version you used?

**Comment by timothysandhu** [comment]
Hey @josesho! 

The older version was v2.5 I think, I downloaded the most recent version about a week before v3.0 was released. 

The code I used was the same all the way through aside from the following difference: 

 multi.two.group.paired<- 
    na.omit(my.data) %>%
    dabest(Group, Measurement, 
           idx = list(c("Group1pre", "Group1post"),c("Group2pre","Group2post")), 
           paired = TRUE, id.col = ID)

  # plot
  multi.two.group.paired.mean_diff <- mean_diff(multi.two.group.paired) ********* this was new with v3.0
  print(plot(multi.two.group.paired.mean_diff,slopegraph = TRUE)) *** with v2.5 I had print(plot(multi.two.group.paired))

Thanks so much
